services:
  db:
    image: postgres:15
    container_name: vcs-postgres

    environment:
      POSTGRES_DB: vcs_sap_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      TZ: Europe/Sofia
      PGTZ: Europe/Sofia

    ports:
      - "5433:5432"

    volumes:
      - vcs_pgdata:/var/lib/postgresql/data

volumes:
  vcs_pgdata: